name: Cleanup Stack
on:
  workflow_dispatch:  # Manual trigger only
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name vw-stack
        aws cloudformation wait stack-delete-complete --stack-name vw-stack